apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-PerformanceTesting"
spec:
    stages:
    - name: "tst"
      sequences:
        - name: testing
          tasks:
          - name: test
            properties:
                teststrategy: performance
          - name: evaluation
          
    - name: "prod"
      sequences:
        - name: testing
          tasks:
          - name: test
            properties:
                teststrategy: performance
          - name: evaluation    